# Uncomment the next line to define a global platform for your project

target 'iosApp (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '14.0'

  # Pods for iosApp (iOS)
  pod 'shared', :path => '../shared'
  pod 'SwiftyDropbox'

end

target 'iosApp (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :macos, '11.0'


  # Pods for iosApp (macOS)
#  pod 'shared', :path => '../shared'
#  podå 'SwiftyDropbox'
end
