ENV['SWIFT_VERSION'] = '5'

target 'MoneyFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  platform :ios, '15.0'

  # Pods for MoneyFlow
  pod 'shared', :path => '../shared'
  pod 'SwiftyDropbox'
end
