ENV['SWIFT_VERSION'] = '5'

target 'MoneyFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '14.0'

  # Pods for MoneyFlow
  pod 'shared', :path => '../shared'
  pod 'SwiftyDropbox'

end
